services:
  octane:
    build:
      context: .
      dockerfile: Dockerfile.franken
      target: prod
      args:
        WWWUSER: "1000"
        WWWGROUP: "1000"
    image: laravel-franken-prod:8.3
    container_name: laravel-franken-prod
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: "3306"
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
    ports:
      - "8080:8000"
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started

  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:7-alpine

volumes:
  dbdata:
