version: "3.9"
services:
  octane:
    build:
      context: .
      dockerfile: Dockerfile.octane
      target: prod
      args:
        PHP_VERSION: "8.3"
        WWWUSER: "1000"
        WWWGROUP: "1000"
    image: laravel-octane-prod:8.3
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
    depends_on:
      - db
      - redis

  web:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx.octane.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.env:/var/www/html/.env:ro
      - ./public:/var/www/html/public:ro
    depends_on:
      - octane

  db:
    image: mysql:8.4
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:7-alpine

volumes:
  dbdata:
