services:
  octane:
    build:
      context: .
      dockerfile: Dockerfile.franken
      target: dev
    container_name: laravel-franken-dev
    ports:
      - "8080:8000"   # http://localhost:8080
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: "3306"
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
    volumes:
      - ./app:/var/www/html
      - ./docker/dev-start-franken.sh:/usr/local/bin/dev-start-franken.sh:ro
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started

  db:
    image: mysql:8.4
    container_name: laravel-db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: laravel-redis
    ports:
      - "6379:6379"

volumes:
  dbdata:
