# Use this ONLY for the very first bootstrap.
# It keeps the octane container alive with 'sleep infinity' so you can install Laravel & deps first.
services:
  octane:
    build:
      context: .
      dockerfile: Dockerfile.octane
      target: dev
      args:
        PHP_VERSION: "8.3"
    image: laravel-octane-dev:init
    container_name: laravel-octane-init
    volumes:
      - ./app:/var/www/html
    command: ["sh", "-lc", "sleep infinity"]
    depends_on:
      - db
      - redis

  web:
    image: nginx:1.27-alpine
    container_name: laravel-octane-web
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx.octane.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - octane

  db:
    image: mysql:8.4
    container_name: laravel-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: laravel-redis
    ports:
      - "6379:6379"

volumes:
  dbdata:
