services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: runtime
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
    depends_on:
      - db
      - redis

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: web
    ports:
      - "8080:80"
    depends_on:
      - php

  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:7-alpine

volumes:
  dbdata:
